swagger: "2.0"
info:
  description: "API for creating and authenticating user/service identities."
  version: "1.0.0"
  title: "TODO"
  license:
    name: "Open Government Licence v3.0"
    url: "http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/"
basePath: "/v1"
tags:
- name: "Identity API"
schemes:
- "https"
parameters:
  id:
    name: id
    description: "The ID of a code list"
    in: path
    type: string
    required: true
  new_identity:
    name: identity
    description: "A new identity"
    in: body
    required: true
    schema:
      $ref: '#/definitions/Identity'
paths:
  /identity:
    post:
      tags:
      - "Identity"
      summary: "Create a new identity"
      description: "Create a new identity"
      parameters:
      - $ref: '#/parameters/new_identity'
      produces:
      - "application/json"
      responses:
        201:
          description: "identity created successfully"
        500:
          description: "TODO"
definitions:
  Identity:
    type: object
    properties:
      id:
        type: string
        description: "unique identifier for user"
      name:
        type: string
        description: "the name of the user"
      email:
        type: string
        description: "the email of the user"
      password:
        type: string
        description: "the password of the user"
      temporary_password:
        type: string
        description: "temporary password for user identity"
      migrated:
        type: boolean
        description: "true if the user has been migrated to identity API, false otherwise"
      deleted:
        type: boolean
        description: "flag to indicate if the user has been deleted"
      user_type:
        type: string
        description: "the user type - TODO: need to define what these are."