// Code generated by moq; DO NOT EDIT
// github.com/matryer/moq

package persistencetest

import (
	"github.com/ONSdigital/dp-identity-api/persistence"
	"sync"
)

var (
	lockDBMockCreate      sync.RWMutex
	lockDBMockGetIdentity sync.RWMutex
)

// DBMock is a mock implementation of DB.
//
//     func TestSomethingThatUsesDB(t *testing.T) {
//
//         // make and configure a mocked DB
//         mockedDB := &DBMock{
//             CreateFunc: func(newIdentity persistence.Identity) (string, error) {
// 	               panic("TODO: mock out the Create method")
//             },
//             GetIdentityFunc: func(email string) (persistence.Identity, error) {
// 	               panic("TODO: mock out the GetIdentity method")
//             },
//         }
//
//         // TODO: use mockedDB in code that requires DB
//         //       and then make assertions.
//
//     }
type DBMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(newIdentity persistence.Identity) (string, error)

	// GetIdentityFunc mocks the GetIdentity method.
	GetIdentityFunc func(email string) (persistence.Identity, error)

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// NewIdentity is the newIdentity argument value.
			NewIdentity persistence.Identity
		}
		// GetIdentity holds details about calls to the GetIdentity method.
		GetIdentity []struct {
			// Email is the email argument value.
			Email string
		}
	}
}

// Create calls CreateFunc.
func (mock *DBMock) Create(newIdentity persistence.Identity) (string, error) {
	if mock.CreateFunc == nil {
		panic("moq: DBMock.CreateFunc is nil but DB.Create was just called")
	}
	callInfo := struct {
		NewIdentity persistence.Identity
	}{
		NewIdentity: newIdentity,
	}
	lockDBMockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	lockDBMockCreate.Unlock()
	return mock.CreateFunc(newIdentity)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//     len(mockedDB.CreateCalls())
func (mock *DBMock) CreateCalls() []struct {
	NewIdentity persistence.Identity
} {
	var calls []struct {
		NewIdentity persistence.Identity
	}
	lockDBMockCreate.RLock()
	calls = mock.calls.Create
	lockDBMockCreate.RUnlock()
	return calls
}

// GetIdentity calls GetIdentityFunc.
func (mock *DBMock) GetIdentity(email string) (persistence.Identity, error) {
	if mock.GetIdentityFunc == nil {
		panic("moq: DBMock.GetIdentityFunc is nil but DB.GetIdentity was just called")
	}
	callInfo := struct {
		Email string
	}{
		Email: email,
	}
	lockDBMockGetIdentity.Lock()
	mock.calls.GetIdentity = append(mock.calls.GetIdentity, callInfo)
	lockDBMockGetIdentity.Unlock()
	return mock.GetIdentityFunc(email)
}

// GetIdentityCalls gets all the calls that were made to GetIdentity.
// Check the length with:
//     len(mockedDB.GetIdentityCalls())
func (mock *DBMock) GetIdentityCalls() []struct {
	Email string
} {
	var calls []struct {
		Email string
	}
	lockDBMockGetIdentity.RLock()
	calls = mock.calls.GetIdentity
	lockDBMockGetIdentity.RUnlock()
	return calls
}
