// Code generated by moq; DO NOT EDIT
// github.com/matryer/moq

package persistencetest

import (
	"github.com/ONSdigital/dp-identity-api/persistence"
	"sync"
)

var (
	lockDBMockGetIdentity  sync.RWMutex
	lockDBMockSaveIdentity sync.RWMutex
)

// DBMock is a mock implementation of DB.
//
//     func TestSomethingThatUsesDB(t *testing.T) {
//
//         // make and configure a mocked DB
//         mockedDB := &DBMock{
//             GetIdentityFunc: func(email string) (persistence.Identity, error) {
// 	               panic("TODO: mock out the GetIdentity method")
//             },
//             SaveIdentityFunc: func(newIdentity persistence.Identity) (string, error) {
// 	               panic("TODO: mock out the SaveIdentity method")
//             },
//         }
//
//         // TODO: use mockedDB in code that requires DB
//         //       and then make assertions.
//
//     }
type DBMock struct {
	// GetIdentityFunc mocks the GetIdentity method.
	GetIdentityFunc func(email string) (persistence.Identity, error)

	// SaveIdentityFunc mocks the SaveIdentity method.
	SaveIdentityFunc func(newIdentity persistence.Identity) (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetIdentity holds details about calls to the GetIdentity method.
		GetIdentity []struct {
			// Email is the email argument value.
			Email string
		}
		// SaveIdentity holds details about calls to the SaveIdentity method.
		SaveIdentity []struct {
			// NewIdentity is the newIdentity argument value.
			NewIdentity persistence.Identity
		}
	}
}

// GetIdentity calls GetIdentityFunc.
func (mock *DBMock) GetIdentity(email string) (persistence.Identity, error) {
	if mock.GetIdentityFunc == nil {
		panic("moq: DBMock.GetIdentityFunc is nil but DB.GetIdentity was just called")
	}
	callInfo := struct {
		Email string
	}{
		Email: email,
	}
	lockDBMockGetIdentity.Lock()
	mock.calls.GetIdentity = append(mock.calls.GetIdentity, callInfo)
	lockDBMockGetIdentity.Unlock()
	return mock.GetIdentityFunc(email)
}

// GetIdentityCalls gets all the calls that were made to GetIdentity.
// Check the length with:
//     len(mockedDB.GetIdentityCalls())
func (mock *DBMock) GetIdentityCalls() []struct {
	Email string
} {
	var calls []struct {
		Email string
	}
	lockDBMockGetIdentity.RLock()
	calls = mock.calls.GetIdentity
	lockDBMockGetIdentity.RUnlock()
	return calls
}

// SaveIdentity calls SaveIdentityFunc.
func (mock *DBMock) SaveIdentity(newIdentity persistence.Identity) (string, error) {
	if mock.SaveIdentityFunc == nil {
		panic("moq: DBMock.SaveIdentityFunc is nil but DB.SaveIdentity was just called")
	}
	callInfo := struct {
		NewIdentity persistence.Identity
	}{
		NewIdentity: newIdentity,
	}
	lockDBMockSaveIdentity.Lock()
	mock.calls.SaveIdentity = append(mock.calls.SaveIdentity, callInfo)
	lockDBMockSaveIdentity.Unlock()
	return mock.SaveIdentityFunc(newIdentity)
}

// SaveIdentityCalls gets all the calls that were made to SaveIdentity.
// Check the length with:
//     len(mockedDB.SaveIdentityCalls())
func (mock *DBMock) SaveIdentityCalls() []struct {
	NewIdentity persistence.Identity
} {
	var calls []struct {
		NewIdentity persistence.Identity
	}
	lockDBMockSaveIdentity.RLock()
	calls = mock.calls.SaveIdentity
	lockDBMockSaveIdentity.RUnlock()
	return calls
}
