// Code generated by moq; DO NOT EDIT
// github.com/matryer/moq

package storetest

import (
	"github.com/ONSdigital/dp-identity-api/models"
	"sync"
)

var (
	lockStorerMockCreateIdentity sync.RWMutex
)

// StorerMock is a mock implementation of Storer.
//
//     func TestSomethingThatUsesStorer(t *testing.T) {
//
//         // make and configure a mocked Storer
//         mockedStorer := &StorerMock{
//             CreateIdentityFunc: func(identity *models.Identity) error {
// 	               panic("TODO: mock out the CreateIdentity method")
//             },
//         }
//
//         // TODO: use mockedStorer in code that requires Storer
//         //       and then make assertions.
//
//     }
type StorerMock struct {
	// CreateIdentityFunc mocks the CreateIdentity method.
	CreateIdentityFunc func(identity *models.Identity) error

	// calls tracks calls to the methods.
	calls struct {
		// CreateIdentity holds details about calls to the CreateIdentity method.
		CreateIdentity []struct {
			// Identity is the identity argument value.
			Identity *models.Identity
		}
	}
}

// CreateIdentity calls CreateIdentityFunc.
func (mock *StorerMock) CreateIdentity(identity *models.Identity) error {
	if mock.CreateIdentityFunc == nil {
		panic("moq: StorerMock.CreateIdentityFunc is nil but Storer.CreateIdentity was just called")
	}
	callInfo := struct {
		Identity *models.Identity
	}{
		Identity: identity,
	}
	lockStorerMockCreateIdentity.Lock()
	mock.calls.CreateIdentity = append(mock.calls.CreateIdentity, callInfo)
	lockStorerMockCreateIdentity.Unlock()
	return mock.CreateIdentityFunc(identity)
}

// CreateIdentityCalls gets all the calls that were made to CreateIdentity.
// Check the length with:
//     len(mockedStorer.CreateIdentityCalls())
func (mock *StorerMock) CreateIdentityCalls() []struct {
	Identity *models.Identity
} {
	var calls []struct {
		Identity *models.Identity
	}
	lockStorerMockCreateIdentity.RLock()
	calls = mock.calls.CreateIdentity
	lockStorerMockCreateIdentity.RUnlock()
	return calls
}
